import type { Metadata } from "next";
import "./globals.css";
import Header from "@/shared/components/Header";
import Filter from "@/shared/widgets/Filter";
import SearchBar from "@/shared/components/SearchBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="mt-20 flex max-w-screen-2xl mx-auto gap-5">
          <aside>
            <Filter />
          </aside>
          <section>
            <SearchBar />
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
